import com.sun.jdi.connect.spi.Connection;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.konek;

public class edit_karyawan extends javax.swing.JFrame {

    public edit_karyawan() {
        initComponents();
    }
    
    
    public void tabelkaryawan() {
    DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Username");
        tbl.addColumn("Nama");
        tbl.addColumn("Gender");
        tbl.addColumn("No Telepon");
        tbl.addColumn("Jabatan");
        data_karyawan.karyawan.setModel(tbl);
        data_karyawan.karyawan.getTableHeader().setBackground(new Color(115,206,191));
        data_karyawan.karyawan.getTableHeader().setForeground(new Color(255,255,255));
        try {
            Statement st = konek.GetConnection().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM data_karyawan");
            while(rs.next ()){
                tbl.addRow(new Object[] {
                rs.getString("username"),
                rs.getString("nama_karyawan"),
                rs.getString("jenis_kelamin"),
                rs.getString("no_hp"),
                rs.getString("jabatan")
                });
            } 
            st.close();
        } catch (Exception e) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_notelp = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_kembali = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("EDIT KARYAWAN");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 10, 180, 40);
        jPanel1.add(txt_username);
        txt_username.setBounds(120, 60, 160, 20);
        jPanel1.add(txt_nama);
        txt_nama.setBounds(120, 90, 160, 22);
        jPanel1.add(txt_notelp);
        txt_notelp.setBounds(120, 120, 160, 20);

        btn_simpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_simpan);
        btn_simpan.setBounds(30, 230, 110, 40);

        jLabel1.setText("Username :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 60, 70, 16);

        jLabel3.setText("Nama :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 90, 40, 16);

        jLabel4.setText("No telp :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 120, 50, 16);

        jLabel5.setText("Jabatan :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 150, 50, 16);

        btn_kembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_kembali.setText("KEMBALI");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btn_kembali);
        btn_kembali.setBounds(180, 230, 120, 40);

        jabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Kasir" }));
        jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabatanActionPerformed(evt);
            }
        });
        jPanel1.add(jabatan);
        jabatan.setBounds(120, 150, 72, 22);

        jLabel6.setText("Gender :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 180, 50, 16);

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));
        jPanel1.add(gender);
        gender.setBounds(120, 180, 94, 22);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Picture1.png"))); // NOI18N
        jPanel1.add(BG);
        BG.setBounds(0, 0, 330, 320);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        try {
            Statement st = konek.GetConnection().createStatement();
            st.executeUpdate("UPDATE data_karyawan SET username='"+txt_username.getText()+"',nama_karyawan='"+txt_nama.getText()+"',no_hp='"+txt_notelp.getText()+"',jabatan='"+jabatan.getSelectedItem()+"', jenis_kelamin='"+gender.getSelectedItem()+"' WHERE username = '"+txt_username.getText()+"' OR nama_karyawan='"+txt_nama.getText()+"';");
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            tabelkaryawan();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal diubah"+e.getMessage());
            this.dispose();
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void jabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jabatanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_simpan;
    public static final javax.swing.JComboBox<String> gender = new javax.swing.JComboBox<>();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public static final javax.swing.JComboBox<String> jabatan = new javax.swing.JComboBox<>();
    public javax.swing.JTextField txt_nama;
    public javax.swing.JTextField txt_notelp;
    public javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
