
import java.sql.Statement;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import koneksi.konek;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JTable;
import javax.swing.JTextField;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ferdi
 */
public class laporanUang extends javax.swing.JFrame {

    public laporanUang() {
        initComponents();
        data_table();
    }
    
      public void data_table() { 
    DefaultTableModel tbl = new DefaultTableModel();
    tbl.addColumn("Bulan");
    tbl.addColumn("Tahun");
    tbl.addColumn("Modal");
    tbl.addColumn("Uang Kotor");
    tbl.addColumn("Uang Bersih");
    tabel.setModel(tbl);
    
    try{
            Statement statement = (Statement)konek.GetConnection().createStatement();
            ResultSet res= statement.executeQuery("SELECT * FROM laporan_keuangan");
            while(res.next())

        while (res.next()) {
            tbl.addRow(new Object[] {
                res.getString("bulan"),
                res.getString("tahun"),
                res.getInt("modal"),
                res.getInt("pemasukan"),
                res.getInt("pemasukan_bersih")
            });
         tabel.setModel(tbl);
        }
            
      }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "salah"); 
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tahunField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        uKotor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        uBersih = new javax.swing.JTextField();
        kembaliButton = new javax.swing.JButton();
        bulanCom = new javax.swing.JComboBox<>();
        bMentah = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Laporan Keuangan");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 10, 320, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Masukkan Bulan dan Tahun");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 70, 200, 20);

        tahunField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tahunField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunFieldActionPerformed(evt);
            }
        });
        jPanel1.add(tahunField);
        tahunField.setBounds(170, 110, 90, 30);

        tabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Bulan", "Tahun", "Uang Kotor", "Uang Bersih"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 150, 760, 240);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(270, 110, 80, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Uang Bersih");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 450, 120, 25);

        uKotor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        uKotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uKotorActionPerformed(evt);
            }
        });
        jPanel1.add(uKotor);
        uKotor.setBounds(210, 410, 200, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Uang Kotor");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 410, 140, 25);

        uBersih.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        uBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uBersihActionPerformed(evt);
            }
        });
        jPanel1.add(uBersih);
        uBersih.setBounds(210, 450, 200, 30);

        kembaliButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kembaliButton.setText("kembali");
        kembaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliButtonActionPerformed(evt);
            }
        });
        jPanel1.add(kembaliButton);
        kembaliButton.setBounds(670, 110, 90, 30);

        bulanCom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bulanCom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        bulanCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulanComActionPerformed(evt);
            }
        });
        jPanel1.add(bulanCom);
        bulanCom.setBounds(30, 110, 130, 30);

        bMentah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buku2.png"))); // NOI18N
        bMentah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMentahMouseClicked(evt);
            }
        });
        jPanel1.add(bMentah);
        bMentah.setBounds(640, 420, 60, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hitunghitung.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(710, 410, 70, 70);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 500);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tahunFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunFieldActionPerformed

    private void uKotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uKotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uKotorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
    String bulanInput = (String) bulanCom.getSelectedItem();
    int tahunInput = Integer.parseInt(tahunField.getText());  
    String sqlQry = "SELECT * FROM laporan_keuangan WHERE bulan = ? AND tahun = ?";
    PreparedStatement statement = konek.GetConnection().prepareStatement(sqlQry);

    statement.setString(1, bulanInput);
    statement.setInt(2, tahunInput);

    ResultSet res = statement.executeQuery();

    DefaultTableModel tbl = new DefaultTableModel();
    tbl.addColumn("Bulan");
    tbl.addColumn("Tahun");
    tbl.addColumn("Modal");
    tbl.addColumn("Uang Kotor");
    tbl.addColumn("Uang Bersih");

    int totalPemasukan = 0;
    int totalPemasukanBersih = 0;

    while (res.next()) {
        int pemasukan = res.getInt("pemasukan");
        int pemasukanBersih = res.getInt("pemasukan_bersih");

        totalPemasukan += pemasukan;
        totalPemasukanBersih += pemasukanBersih;

        tbl.addRow(new Object[]{
                res.getString("bulan"),
                res.getInt("tahun"),
                res.getInt("modal"),
                pemasukan,
                pemasukanBersih
        });
    }
    tabel.setModel(tbl);

   
    uKotor.setText(String.valueOf(totalPemasukan));
    uBersih.setText(String.valueOf(totalPemasukanBersih));

} catch (Exception e) {
    JOptionPane.showMessageDialog(rootPane, "Error: " + e.getMessage());
    e.printStackTrace();
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void uBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uBersihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uBersihActionPerformed

    private void kembaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliButtonActionPerformed
        // TODO add your handling code here:
             dashboard_admin das = new dashboard_admin();
        das.setVisible(true);
        dispose();
    }//GEN-LAST:event_kembaliButtonActionPerformed

    private void bulanComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulanComActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bulanComActionPerformed

    private void bMentahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMentahMouseClicked
          BelanjaMentah belanja = new BelanjaMentah();
        belanja.setVisible(true);
        dispose();
    }//GEN-LAST:event_bMentahMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       KeuntunganFrame untung = new KeuntunganFrame();
       untung.setVisible(true);
       dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporanUang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporanUang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporanUang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporanUang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporanUang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bMentah;
    private javax.swing.JComboBox<String> bulanCom;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembaliButton;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tahunField;
    private javax.swing.JTextField uBersih;
    private javax.swing.JTextField uKotor;
    // End of variables declaration//GEN-END:variables
}
